apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  template:
    spec:
      containers:
        # renovate: datasource=docker depName=linuxserver/qbittorrent versioning=semver
        - image: linuxserver/qbittorrent:5.2.3
          name: qbittorrent
