apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldpinger
  namespace: monitoring
spec:
  values:
    image:
      repository: bloomberg/goldpinger
      # renovate: datasource=docker depName=bloomberg/goldpinger versioning=semver
      tag: "3.10.2"
    goldpinger:
      udp:
        enabled: true
    extraEnv:
      - name: HOSTS_TO_RESOLVE
        value: "ya.ru"
    serviceMonitor:
      enabled: true
