---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin-secrets
    app.kubernetes.io/instance: apps-jellyfin
    app.kubernetes.io/managed-by: kustomize
spec:
  refreshInterval: 1h
  secretStoreRef:
      name: vaultwarden
      kind: ClusterSecretStore
  target:
    name: jellyfin
  data:
    - secretKey: http_proxy
      remoteRef:
        key: 3a1ae551-e742-4756-8018-49d4f37619b5
        property: http_proxy
    - secretKey: https_proxy
      remoteRef:
        key: 3a1ae551-e742-4756-8018-49d4f37619b5
        property: https_proxy
